Path publisher
tue-robotics/emc_system pull request #20
Opened 2023-04-17 12:37 UTC by ThijsBeurskensTUE

2023-04-17 13:30 UTC, PetervDooren requested changes
#TODO update emc-env to ensure installation of the required packages:

- nav_msgs
- tf2
- tf2_ros

2023-04-17 13:30 UTC, PetervDooren commented on src/communication.cpp
> +    mapconfig.mapOffsetY = (msg->width * mapconfig.mapResolution / 2) * sin(yaw)+(msg->height * mapconfig.mapResolution / 2) * cos(yaw) + msg->origin.position.y;
You encountered an issue with the origin of the world not matching the map. Could this be the cause? This formula might not be correct

2023-04-17 13:30 UTC, PetervDooren commented on src/io.cpp
> +        if ((*it).size() < 2)
```suggestion
        if (it->size() != 2)
```
Also break if they added more then 2 values. That is also not intended behaviour and probably indicates that something went wrong.

2023-04-17 13:30 UTC, PetervDooren commented on src/io.cpp
> +        }
What if the mapdata is not initialised? Do you still publish in map frame

2023-04-17 13:30 UTC, PetervDooren commented on src/io.cpp
> +        ROS_ERROR_STREAM("not enough valid points");
specify how many points were found. That helps debugging. In this case you might also print out these points. e.g.

"not enough valid points. no valid points"
"not enough valid points. only got [x1,y1]"

2023-04-17 13:42 UTC, PetervDooren commented on src/io.cpp
> +        }
I'll rephrase. I think its better to throw an error and return false in this situation.

2023-04-17 13:43 UTC, PetervDooren commented on src/io.cpp
> +        ROS_ERROR_STREAM("not enough valid points");
But a single, general check on the size is sufficient.

2023-04-18 12:43 UTC, ThijsBeurskensTUE commented on src/communication.cpp
> +    mapconfig.mapOffsetY = (msg->width * mapconfig.mapResolution / 2) * sin(yaw)+(msg->height * mapconfig.mapResolution / 2) * cos(yaw) + msg->origin.position.y;
This formula correctly finds the centre of the map, but the orgin of the simulator is one pixel off centre. I think it's better to correct the simulator to have the origin in the centre than to introduce this offset everywhere.

2023-05-03 13:35 UTC, KdVos approved these changes

2023-05-03 13:36 UTC, merged