Fix communication object
tue-robotics/emc_system pull request #8
Opened 2022-09-29 10:09 UTC by MatthijsBurgh

2022-09-29 10:11 UTC, MatthijsBurgh commented
Please perform an integrated test. I just tested this with the small example from https://github.com/tue-robotics/emc_system/issues/6#issuecomment-1261861952

2022-09-30 07:42 UTC, KdVos commented
Tested your changes using the full example we provide to the students. Somehow 
the changes subtly breaks the full example. Instead of turning on the first object that is encountered, the robot stops moving and remain stationary. Will investigate what is happening.

2022-09-30 07:58 UTC, KdVos commented on src/communication.cpp
> +    sub_bumper_b_ = nh.subscribe(bumper_f_sub_options);
```suggestion
    sub_bumper_b_ = nh.subscribe(bumper_b_sub_options);
```
;)

2022-09-30 08:07 UTC, KdVos requested changes

2022-09-30 08:07 UTC, KdVos commented on src/communication.cpp
> +    ros::SubscribeOptions bumper_b_sub_options = ros::SubscribeOptions::create<std_msgs::Bool>("/" + robot_name + "/base_b_bumper_sensor", 1, boost::bind(&Communication::bumperbCallback, this, _1), r
```suggestion
    ros::SubscribeOptions bumper_b_sub_options = ros::SubscribeOptions::create<std_msgs::Bool>("/" + robot_name + "/base_b_bumper_sensor", 1, boost::bind(&Communication::bumperbCallback, this, _1), ros::VoidPtr(), &bumper_b_cb_queue_);
```

2022-09-30 08:07 UTC, KdVos commented on src/communication.cpp
> +    ros::SubscribeOptions bumper_f_sub_options = ros::SubscribeOptions::create<std_msgs::Bool>("/" + robot_name + "/base_f_bumper_sensor", 1, boost::bind(&Communication::bumperfCallback, this, _1), r
```suggestion
    ros::SubscribeOptions bumper_f_sub_options = ros::SubscribeOptions::create<std_msgs::Bool>("/" + robot_name + "/base_f_bumper_sensor", 1, boost::bind(&Communication::bumperfCallback, this, _1), ros::VoidPtr(), &bumper_f_cb_queue_);
```

2022-09-30 08:07 UTC, KdVos commented
Apart from these minor oversights it seems to work as expected. Thanks!

2022-09-30 08:18 UTC, MatthijsBurgh commented on src/communication.cpp
> +    sub_bumper_b_ = nh.subscribe(bumper_f_sub_options);
This is why you should review code.

2022-09-30 08:27 UTC, KdVos approved these changes

2022-09-30 08:47 UTC, merged